apiVersion: v1
kind: PersistentVolume
metadata:
  name: openclaw-workspace
  labels:
    type: local
    app: openclaw
spec:
  storageClassName: standard
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/Users/jianhui/projects/playground/godlike-mcp-tooler-chad/openclaw-assets/workspace"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openclaw-workspace
  namespace: openclaw
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      app: openclaw
      type: workspace
